#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HISTORY_FILE="$ROOT_DIR/.runtime/quality/history.csv"
OUT_DIR="$ROOT_DIR/docs/quality"
OUT_FILE="$OUT_DIR/baseline.env"

if [[ ! -f "$HISTORY_FILE" ]]; then
  echo "quality-baseline: no history file. Run ./tools/quality-metrics.sh first."
  exit 1
fi

mkdir -p "$OUT_DIR"

latest_line="$(tail -n 1 "$HISTORY_FILE")"
IFS=',' read -r ts _ css_max_line _ css_dupe _ js_max_line _ js_ifs js_ternaries js_state_mutations _ _ dist_bytes dist_max_line dist_repl <<< "$latest_line"

cat > "$OUT_FILE" <<EOF
# Generated by tools/quality-baseline.sh on $ts
# Update only when intentionally accepting a new quality baseline.

BASELINE_CSS_DUPE=$css_dupe
BASELINE_JS_IFS=$js_ifs
BASELINE_JS_TERNARIES=$js_ternaries
BASELINE_JS_MAX_LINE=$js_max_line
BASELINE_JS_STATE_MUTATIONS=$js_state_mutations
BASELINE_DIST_BYTES=$dist_bytes
BASELINE_DIST_MAX_LINE=$dist_max_line
BASELINE_DIST_REPL=$dist_repl

# Allowed deltas above baseline (strict anti-regression defaults)
ALLOW_CSS_DUPE_DELTA=0
ALLOW_JS_IFS_DELTA=0
ALLOW_JS_TERNARIES_DELTA=0
ALLOW_JS_MAX_LINE_DELTA=8
ALLOW_JS_STATE_MUTATIONS_DELTA=0
ALLOW_DIST_BYTES_DELTA=3500
ALLOW_DIST_MAX_LINE_DELTA=30
ALLOW_DIST_REPL_DELTA=0
EOF

echo "quality-baseline: written $OUT_FILE"
